import { useCallback, useRef, useState } from "react";
import { motion } from "framer-motion";
import { FileDown, UploadCloud, Key, AlertCircle } from "lucide-react";

import { useReportStore } from "@/hooks/useReportStore";
import type { Report } from "@/types/report";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Alert } from "@/components/ui/alert";

export function EnhancedUpload() {
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const { setReport, setPublicKeyHex, setUploadError, uploadError, reset, publicKeyHex } = useReportStore();
  const [hovered, setHovered] = useState(false);
  const [fileLoaded, setFileLoaded] = useState(false);

  const parseFile = useCallback(async (file: File) => {
    try {
      const text = await file.text();
      const parsed = JSON.parse(text) as Report;
      setReport(parsed);
      setUploadError(undefined);
      setFileLoaded(true);
    } catch (error) {
      console.error(error);
      setReport(undefined);
      setFileLoaded(false);
      setUploadError("Unable to parse JSON. Please upload a valid compliance attestation report.");
    }
  }, [setReport, setUploadError]);

  const handleFiles = (files: FileList | null) => {
    if (!files || files.length === 0) return;
    reset();
    parseFile(files[0]);
  };

  const handlePublicKeyLoad = useCallback(async () => {
    if (!fileInputRef.current) return;
    const keyFileInput = document.createElement("input");
    keyFileInput.type = "file";
    keyFileInput.accept = "text/plain";
    keyFileInput.onchange = async (e) => {
      const file = (e.target as HTMLInputElement).files?.[0];
      if (file) {
        const text = await file.text();
        setPublicKeyHex(text.trim());
      }
    };
    keyFileInput.click();
  }, [setPublicKeyHex]);

  return (
    <div className="space-y-6">
      {/* Report Upload */}
      <Card
        className="relative overflow-hidden"
        onDragOver={(e) => {
          e.preventDefault();
          setHovered(true);
        }}
        onDragLeave={(e) => {
          e.preventDefault();
          setHovered(false);
        }}
        onDrop={(e) => {
          e.preventDefault();
          setHovered(false);
          handleFiles(e.dataTransfer.files);
        }}
      >
        <CardHeader>
          <CardTitle>Upload Aegis Report</CardTitle>
          <CardDescription>
            Upload the aegis-report.json file generated by the Docker agent
          </CardDescription>
        </CardHeader>
        <CardContent>
          <motion.div
            animate={{
              borderColor: hovered ? "rgba(129, 140, 248, 1)" : "rgba(255,255,255,0.08)",
              scale: hovered ? 1.01 : 1,
            }}
            className="flex flex-col items-center gap-4 rounded-2xl border-2 border-dashed border-border/80 bg-muted/20 px-6 py-10 text-center"
          >
            <UploadCloud className="h-10 w-10 text-primary" />
            <div>
              <p className="text-lg font-semibold">Drop your aegis-report.json</p>
              <p className="text-sm text-muted-foreground">
                Generated from the Docker agent scan
              </p>
            </div>
            <Button onClick={() => fileInputRef.current?.click()} className="gap-2">
              <FileDown className="h-4 w-4" /> Choose JSON file
            </Button>
            <input
              ref={fileInputRef}
              type="file"
              accept="application/json"
              className="hidden"
              onChange={(event) => handleFiles(event.target.files)}
            />
            {fileLoaded && (
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                className="flex items-center gap-2 rounded-lg bg-emerald-500/20 px-4 py-2 text-sm text-emerald-300"
              >
                <AlertCircle className="h-4 w-4" /> Report loaded successfully
              </motion.div>
            )}
            {uploadError && (
              <Alert type="error" title="Upload failed" description={uploadError} />
            )}
          </motion.div>
        </CardContent>
      </Card>

      {/* Credentials Input */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Key className="h-5 w-5" /> Verification Credentials
          </CardTitle>
          <CardDescription>
            Provide your public key (pub.key) to verify the report signature
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="public-key">Public Key (hex)</Label>
            <div className="flex gap-2">
              <Input
                id="public-key"
                placeholder="Paste your public key or load from file"
                value={publicKeyHex}
                onChange={(e) => setPublicKeyHex(e.target.value)}
                className="font-mono text-xs"
              />
              <Button variant="outline" onClick={handlePublicKeyLoad} className="gap-2">
                <FileDown className="h-4 w-4" /> Load
              </Button>
            </div>
            <p className="text-xs text-muted-foreground">
              This is the public key from ~/.kratos/keys/pub.key generated by the Docker agent
            </p>
          </div>
          {publicKeyHex && publicKeyHex.length >= 32 && (
            <motion.div
              initial={{ opacity: 0, y: 5 }}
              animate={{ opacity: 1, y: 0 }}
              className="rounded-lg bg-emerald-500/20 px-4 py-2 text-sm text-emerald-300"
            >
              ✓ Public key ready for verification
            </motion.div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
